version: 2
plugins:
  sonar-php:
    enabled: true
    checks:
      php:S131:
        enabled: false
      php:S1192:
        enabled: false
  phpmd:
    enabled: true
    checks:
      CleanCode/ElseExpression:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      Naming/LongVariable:
        enabled: false
      Naming/ShortVariable:
        enabled: false
  phan:
    enabled: true
    checks:
      dead-code-detection:
        enabled: true
    config:
      file_extensions: "php"
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/contrib/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "src/Minecraft/Dynmap/dynmap.js"